name: Build Eleventy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js current
        uses: actions/setup-node@v3
        with:
          node-version: current

      - run: yarn install
      - name: Install dependencies & build
        run: yarn build
        env: 
          REPO_URL: https://github.com/WyattH99/WyattH99.github.io
          WEB_PATH_PREFIX: /WyattH99.github.io/
          WEB_ROOT_URL: https://WyattH99.github.io/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          #publish_branch is the branch in the repository.
          #this is where you need to point GitHub pages
          publish_branch: gh-pages